### PR TITLE
Information model

### PR DESCRIPTION
**Pull request by MichaelDrogalis**
Adds an information model. We should generate the README from this file at a later point.

### CODE REVIEW

**Comment by lbradstreet** [comment]
This is great. Thanks for getting one of them done. A few thoughts:
1. I think we need separate key definitions in the model for each task type. We could possibly do it via a shared map where we lookup the common entries. The reason why I worry is perhaps we have different constraints/optionality for task-map keys depending on the task case. One example is that kafka/topic is optional for write-messages, as we can rely on the message keys. Same story with kafka/partition.
2. We should have a task-map summary/description, which is currently missing from the information model map.
3. We may need to specify other constraints like min/max-peers, even though they are not strictly kafka keys.

**Comment by lbradstreet** [comment]
I realise that you're going for bundle re-use, but I think the main thing is that the task defines what's necessary, and then the task bundles restrict that further. I'd rather not even include task-bundle keys in the information model as they are a higher level concept. Rather, I'd just let them be the ordering of the keys for the documentation.

**Comment by lbradstreet** [comment]
There were also a few error around optionality of partitions/topics, though these may have come from the README.

I've made these changes, and built a test to check whether the ordering keys exist.

From here all we really need to do is build some task bundles on top which include the task-bundle default keys, and then all of the information model defaults can be added to them automatically.

Let me know what you think of this structure. I think it's going to serve us better as we build out task bundles - what we care about in the plugin information model is what the plugin expects, then we can build task bundles that work under those defined constraints/defaults.

**Comment by lbradstreet** [comment]
Your turn to re-review and merge

**Comment by lbradstreet** [comment]
One other thing that I think would be useful with these information models is auto CHANGES.MD generation. When the documentation changes, we should provide an easy way to see what has changed in the information model.

A very common activity for iOS developers is to look at the API diffs from one iOS version to another. I think it'll be quite a powerful use of the information model. Perhaps we could even provide a tool via the cheat sheet that allows you to compare any two versions X and Y of the plugins/onyx-core, and gives you an information model diff so you can see what has been deprecated/added as you upgrade from version X to version Y.

**Comment by MichaelDrogalis** [comment]
@lbradstreet The reason I'm sharing entries across tasks it that namespaced keys are generally assuming to be globally unique within a system (Onyx as a whole, in this case). This is partially my fault since I originally named them. The tricky thing here is that, if we want to insert this information model into Datomic, we can't have two entries looked up by the same keyword (`:kafka/topic`) with different definitions.

**Comment by MichaelDrogalis** [comment]
I think this structure is better overall, and the discussion about uniquely named keys is orthogonal. We can get back to that at another time.

**Comment by lbradstreet** [comment]
This is an excellent point, that I hadn't considered. That said, I think it's fine - we just won't be able to uniquely identify them by the namespaced keyword. Unless I misunderstand your point, I think datomic should allow this just fine.

**Pull request merged**
