### PR TITLE
added config options for fetch size and request size

### PR DESCRIPTION
**Pull request by prismofeverything**
These are the two changes I needed to make to be able to send and receive messages above the default size.  I have it tested and working locally, let me know any questions.  Thanks!

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
Build fails with:

``` clojure
15-Nov-10 03:34:49 localhost WARN [onyx.peer.task-lifecycle] - 
                                     java.lang.Thread.run              Thread.java:  745
       java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
        java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                      java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                                      ...                               
                      clojure.core/binding-conveyor-fn/fn                 core.clj: 1916
          onyx.log.commands.common/start-new-lifecycle/fn               common.clj:  138
             onyx.peer.task-lifecycle.TaskLifeCycle/start       task_lifecycle.clj:  663
onyx.peer.task-compile/compile-after-batch-task-functions         task_compile.clj:   92
       onyx.peer.task-compile/compile-lifecycle-functions         task_compile.clj:   59
                                      clojure.core/reduce                 core.clj: 6519
                              clojure.core.protocols/fn/G            protocols.clj:   13
                                clojure.core.protocols/fn            protocols.clj:  101
                        clojure.core.protocols/seq-reduce            protocols.clj:   31
                              clojure.core.protocols/fn/G            protocols.clj:   19
                                clojure.core.protocols/fn            protocols.clj:  136
                                                      ...                               
    onyx.peer.task-compile/compile-lifecycle-functions/fn         task_compile.clj:   61
           onyx.peer.task-compile/resolve-lifecycle-calls         task_compile.clj:   28
                               onyx.peer.operation/kw->fn            operation.clj:   34
                                     clojure.core/ex-info                 core.clj: 4593
clojure.lang.ExceptionInfo: Could not resolve symbol on the classpath, did you require the file that contains the symbol :onyx.plugin.output-test/in-calls?
    data: {:kw :onyx.plugin.output-test/in-calls}

15-Nov-10 03:34:49 localhost INFO [onyx.peer.task-lifecycle] - [628d120f-6c82-4b57-a192-49d117c39bdb] Stopping Task LifeCycle for null
15-Nov-10 03:34:49 localhost WARN [onyx.peer.task-lifecycle] - 
                              java.lang.Thread.run              Thread.java:  745
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 1916
   onyx.log.commands.common/start-new-lifecycle/fn               common.clj:  138
      onyx.peer.task-lifecycle.TaskLifeCycle/start       task_lifecycle.clj:  690
           onyx.peer.task-lifecycle/build-pipeline       task_lifecycle.clj:  602
                              clojure.core/ex-info                 core.clj: 4593
clojure.lang.ExceptionInfo: Failed to resolve or build plugin on the classpath, did you require/import the file that contains this plugin?
    data: {:symbol :onyx.plugin.kafka/write-messages, :exception #error {
           :cause "Could not resolve symbol on the classpath, did you require the file that contains the symbol :onyx.plugin.output-test/serialize-segment?"
           :data {:kw :onyx.plugin.output-test/serialize-segment}
           :via
           [{:type clojure.lang.ExceptionInfo
             :message "Could not resolve symbol on the classpath, did you require the file that contains the symbol :onyx.plugin.output-test/serialize-segment?"
             :data {:kw :onyx.plugin.output-test/serialize-segment}
             :at [clojure.core$ex_info invoke "core.clj" 4593]}]
           :trace
           [[clojure.core$ex_info invoke "core.clj" 4593]
            [onyx.peer.operation$kw__GT_fn invoke "operation.clj" 34]
            [onyx.plugin.kafka$write_messages invoke "kafka.clj" 285]
            [clojure.lang.Var invoke "Var.java" 379]
            [onyx.peer.task_lifecycle$build_pipeline invoke "task_lifecycle.clj" 596]
            [onyx.peer.task_lifecycle.TaskLifeCycle start "task_lifecycle.clj" 690]
            [onyx.log.commands.common$start_new_lifecycle$fn__12345 invoke "common.clj" 138]
            [clojure.core$binding_conveyor_fn$fn__4444 invoke "core.clj" 1916]
            [clojure.lang.AFn call "AFn.java" 18]
            [java.util.concurrent.FutureTask run "FutureTask.java" 266]
            [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
            [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
            [java.lang.Thread run "Thread.java" 745]]}}
```

**Comment by MichaelDrogalis** [comment]
(Updated to 0.8.0-SNAPSHOT to work around missing `:data` key we ran into earlier.)

**Comment by prismofeverything** [comment]
Ah, when running both `lein test` or `lein midje` the process just hangs on starting Aeron.  Happy to fix if you tell me how to run tests successfully!  

The changes were pretty minimal as well, not sure how they could have caused the given error... looks like it can't find the symbol `:onyx.plugin.output-test/serialize-segment`?

**Comment by prismofeverything** [comment]
Ah, I see now your test calls `take-until-done` directly.  It now takes the original three arguments as well as the fourth with options.

**Comment by MichaelDrogalis** [comment]
Great. Only other change I'd like to see is the duplicate `307200` value put into the defaults map in `kafka.clj`, and a corresponding update to the README.md documentation about the existence of this new param. Thanks!

**Comment by prismofeverything** [comment]
Alright, done

**Comment by MichaelDrogalis** [comment]
Thanks!

**Pull request merged**
