### PR TITLE
Use first broker in list, rather than looking specifically for a plai…

### PR DESCRIPTION
**Pull request by smawdsleyamaze**
…ntext broker.

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
@smawdsleyamaze Thanks! Can you change the base to master and resolve conflicts?

**Comment by smawdsleyamaze** [comment]
@MichaelDrogalis This is actually resolved already in master branch.. that function has moved to /src/onyx/kafka/helpers.clj and contains the same fix. Can this just be applied to 0.10.x?

**Comment by MichaelDrogalis** [comment]
@smawdsleyamaze I cut a release - 0.10.0.1 containing the fix. Let me know how you go!

**Comment by smawdsleyamaze** [comment]
Thanks for this @MichaelDrogalis .. looks good!

**Comment by MichaelDrogalis** [comment]
Absolutely!

**Pull request closed without merging**
