### PR TITLE
Fix issue with embedded kafka test advertisement in README

### PR DESCRIPTION
**Pull request by enragedginger**
Also fixed issue where the log-dir parameter in the mock-kafka test-utils function was not being used.

### CODE REVIEW

**Comment by enragedginger** [comment]
Is there anything preventing this from being approved?

**Comment by MichaelDrogalis** [comment]
cc @lbradstreet

**Comment by lbradstreet** [comment]
Thanks @enragedginger. Looks good. Sorry it escaped our attention!

**Comment by lbradstreet** [comment]
By the way, we have moved away from using embedded kafka for CI, and generally local purposes, as we found it too flaky to use Kafka in this way. 0.10.x will only support running the tests against the  setup defined in docker-compose.yml.

**Comment by enragedginger** [comment]
That's good to know. Thanks, everybody!

**Pull request merged**
